stages:
  - build
#  - test
#  - deploy

build-image:
  stage: build
  script:
    - docker build -t web-api .
#    - docker run registry.gitlab.com/ehean/mbta-tracker:latest pytest
    - docker tag web-api registry.gitlab.com/ehean/mbta-tracker/web-api
    - docker push registry.gitlab.com/ehean/mbta-tracker/web-api
