---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "mbta-tracker-dev-service"
  namespace: "default"
  labels:
    app: "mbta-tracker-dev"
spec:
  ports:
  - protocol: "TCP"
    port: 5002
    targetPort: 5002
  selector:
    app: "mbta-tracker-dev"
  type: "LoadBalancer"
  loadBalancerIP: ""
